const mongoose = require('mongoose');

// ─── Trip Schema ──────────────────────────────────────────────────────────────
// autoIndex is controlled globally in database.js (off in production).
// The || mongoose.models.X guard prevents OverwriteModelError on hot-reloads
// (e.g. nodemon) — it reuses the already-registered model instead of
// redefining it, which would otherwise clear in-memory model state.

const tripSchema = new mongoose.Schema({
  // Owner of this trip — matches UserProfile.user_id (auth-provider UID).
  // Indexed so queries scoped to a single user (the common case) stay fast.
  user_id: {
    type: String,
    required: true,
    trim: true,
    index: true,
  },
  name:        { type: String, required: true, trim: true },
  destination: { type: String, required: true, trim: true },
  startDate:   { type: Date },
  endDate:     { type: Date },
  currency: {
    type: String,
    default: 'USD',
    enum: ['USD','EUR','GBP','AUD','NZD','JPY','CAD','SGD','THB','IDR','MYR','PHP','VND','INR','CNY','HKD','KRW'],
  },
  budget: { type: Number, default: 0, min: 0 },
  notes:  { type: String, default: '' },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  // Disable autoIndex at schema level — inherits the global setting from
  // database.js but this makes it explicit and prevents accidental index
  // creation if the schema is used outside the normal boot path.
  autoIndex: process.env.NODE_ENV !== 'production',
});

// ─── Expense Schema ───────────────────────────────────────────────────────────
const EXPENSE_CATEGORIES = [
  'accommodation', 'flights', 'food', 'transport', 'shopping',
  'activities', 'health', 'communication', 'visa', 'insurance', 'other',
];

const expenseSchema = new mongoose.Schema({
  // Owner of this expense — denormalised from the parent trip so that
  // per-user expense queries don't require a join through Trip.
  // Always set to the same user_id as the parent trip on creation.
  user_id:       { type: String, required: true, trim: true, index: true },
  tripId:        { type: mongoose.Schema.Types.ObjectId, ref: 'Trip', required: true },
  category:      { type: String, required: true, enum: EXPENSE_CATEGORIES },
  description:   { type: String, default: '', trim: true },
  amount:        { type: Number, required: true, min: 0 },
  date:          { type: Date, default: Date.now },
  paymentMethod: { type: String, default: 'cash', enum: ['cash', 'card', 'digital', 'other'] },
  notes:         { type: String, default: '' },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  autoIndex: process.env.NODE_ENV !== 'production',
});

// Compound index: the most common query is "expenses for a specific trip
// belonging to a specific user", so index both fields together.
expenseSchema.index({ user_id: 1, tripId: 1 });

// ─── UserProfile Schema ───────────────────────────────────────────────────────
// user_id is a unique alphanumeric string (e.g. Firebase UID or similar).
// It is stored as a plain string rather than ObjectId so it can be set by
// the caller (auth provider) rather than generated by MongoDB.
// A sparse unique index is created on email so two profiles cannot share
// the same address, while still allowing the field to be absent in legacy docs.

const MEMBER_LEVELS = ['basic', 'premium'];

const userProfileSchema = new mongoose.Schema({
  // External identifier supplied by the auth provider (Firebase UID, Auth0 sub, etc.)
  // unique: true ensures no two profiles share the same id.
  user_id: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    match: [/^[a-zA-Z0-9]+$/, 'user_id must be alphanumeric'],
  },

  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true,
    match: [/^[^\s@]+@[^\s@]+\.[^\s@]+$/, 'Please provide a valid email address'],
  },

  name: {
    type: String,
    required: true,
    trim: true,
  },

  // Whether the user has verified their email address
  verified: {
    type: Boolean,
    default: false,
  },

  // Subscription / access tier
  memberLevel: {
    type: String,
    enum: MEMBER_LEVELS,
    default: 'basic',
  },
}, {
  // Adds createdAt and updatedAt automatically
  timestamps: true,
  toJSON: { virtuals: true },
  autoIndex: process.env.NODE_ENV !== 'production',
});

// ─── Safe model registration ──────────────────────────────────────────────────
// mongoose.models.X is populated after the first mongoose.model() call.
// On hot-reload (nodemon), the module is re-evaluated but mongoose retains its
// model registry — so we reuse the existing registered model rather than
// calling mongoose.model() again, which would throw OverwriteModelError.
const Trip        = mongoose.models.Trip        || mongoose.model('Trip',        tripSchema);
const Expense     = mongoose.models.Expense     || mongoose.model('Expense',     expenseSchema);
const UserProfile = mongoose.models.UserProfile || mongoose.model('UserProfile', userProfileSchema);

module.exports = { Trip, Expense, UserProfile, EXPENSE_CATEGORIES, MEMBER_LEVELS };